### ISSUE TITLE
Add `dbt/adapters/sqlite/__version__.py`

### ISSUE THREAD

**Issue by edgarrmondragon** [codeforkjeff/dbt-sqlite#12]
Adding the file with a variable `version` set to the package version allows printing the adapter version along when `dbt --version` is invoked.

Current behavior:

```console
$ dbt --version
installed version: 1.0.0
   latest version: 1.0.0

Up to date!

Plugins:
```

Expected behavior:

```console
$ dbt --version
installed version: 1.0.0
   latest version: 1.0.0

Up to date!

Plugins:
  - sqlite: 0.2.2
```

Reference: https://docs.getdbt.com/docs/contributing/building-a-new-adapter#__version__py

**Comment by codeforkjeff** [comment]
Thank you for catching this! I've committed the change.

The docs for building a new adapter have been updated quite a bit since I last looked at them. I should review it again and see if there's anything else I should add, then I'll make a new release. Hopefully I'll get to it in the next few days.
