### ISSUE TITLE
Running out of memory when running `dbt seed` with large CSV

### ISSUE THREAD

**Issue by killermouse0** [codeforkjeff/dbt-sqlite#19]
I have a 2.1GB CSV file in the `seeds` directory. When I run `dbt seed`, it works for a while then crashes:

```
$ dbt seed
18:40:13  Running with dbt=1.1.0
18:40:14  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 173 macros, 0 operations, 2 seed files, 0 sources, 0 exposures, 0 metrics
18:40:14
18:40:14  Concurrency: 1 threads (target='dev')
18:40:14
18:40:14  1 of 2 START seed file main.DATA ............................................. [RUN]
[1]    702783 killed     dbt seed
$ /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Running `dmesg` shows:
```
[553066.736092] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=user.slice,mems_allowed=0,global_oom,task_memcg=/,task=dbt,pid=709386,uid=1000
[553066.736147] Out of memory: Killed process 709386 (dbt) total-vm:4719592kB, anon-rss:3142892kB, file-rss:8kB, shmem-rss:4kB, UID:1000 pgtables:6252kB oom_score_adj:0
[553067.100938] oom_reaper: reaped process 709386 (dbt), now anon-rss:0kB, file-rss:0kB, shmem-rss:4kB
```

Running on a system with limited RAM, obviously, but is there any reason that it would run out of RAM while inserting data into DB ?

Thanks for any pointers!

**Comment by edgarrmondragon** [comment]
My 2¢ from https://docs.getdbt.com/docs/building-a-dbt-project/seeds#faqs:

> Seeds should **not** be used to load raw data (for example, large CSV exports from a production database).
> 
> Since seeds are version controlled, they are best suited to files that contain business-specific logic, for example a list of country codes or user IDs of employees.
> 
> Loading CSVs using dbt's seed functionality is not performant for large files. Consider using a different tool to load these CSVs into your data warehouse.

That said, there are a few tools like https://github.com/simonw/csvs-to-sqlite or even the `.import` function in the sqlite shell: https://www.sqlite.org/cli.html#importing_files_as_csv_or_other_formats

**Comment by codeforkjeff** [comment]
I'm pretty sure dbt loads the entire contents of seed files into memory, which is why you're seeing the OOM error. This is in dbt-core, so it's not an issue specific to this adapter.

I agree with @edgarrmondragon, if you can use .import in the sqlite CLI program, that would be the ideal solution. 

If you really need to use dbt seed for some reason, you can split the file into several files. On Linux, you might be able to do this using the "split" program, and then using "cat" to add the header row to the files that need them. Then you can union them together as the first step in your pipeline.

**Comment by killermouse0** [comment]
All clear! Thanks for the quick answer, @edgarrmondragon and @codeforkjeff!
